### ISSUE TITLE
Request tests

### ISSUE THREAD

**Issue by beauby** [davydovanton/rspec-hanami#2]
Any plan to support request tests with Hanami? (sequences of black-box request-response cycles going through the whole Hanami app including middlewares)

**Comment by davydovanton** [comment]
Hello @beauby, I open for any ideas and that's why yes, why not. Do you have any ideas how we can do it?

**Comment by beauby** [comment]
Here is a little helper I threw together last night: https://gist.github.com/beauby/fe02ecd48f68bcaa11033e08445af36f (I then heard about the `Rack::Test` gem, which does pretty much the same thing, but is not maintained anymore).

**Comment by davydovanton** [comment]
interesting. I'll try to implement this as soon as possible. Thanks!

**Comment by davydovanton** [comment]
Thanks, I created this. Now you can use request helpers in tests 🎉
