### ISSUE TITLE
Have_filed matcher conflicts with Capybara 

### ISSUE THREAD

**Issue by ADodulad** [davydovanton/rspec-hanami#21]
When using `have_field` matcher in unit tests and running and unit and integration tests altogether `have_field` matcher from Capybara's matchers would be used since `feature_spec` loads Capybara's matchers after `RSpec::Hanami` matchers has been loaded in `spec_helper`.

Proposal: rename `have_field` matcher to `have_input`.

**Comment by davydovanton** [comment]
hey, thanks for report. WDYT to rename it to `have_form_field`? And could you prepare PR with this changes?

**Comment by ADodulad** [comment]
Take a look - #22. Seems to fix this problem.
